### ISSUE TITLE
JS errors on my 2016-ish MacBook Air

### ISSUE THREAD

**Issue by Deleplace** [tomayac/joy-con-webhid#1]
My JoyCons arre connected in Bluetooth to the computer:
![image](https://user-images.githubusercontent.com/13508141/101764824-cf4dcd80-3ae0-11eb-96b7-24b2840d6eed.png)

However Chrome and Firefox fail on `navigator.hid`:
![image](https://user-images.githubusercontent.com/13508141/101765077-1c31a400-3ae1-11eb-8f92-d67d077b4c93.png)
![image](https://user-images.githubusercontent.com/13508141/101765023-0a500100-3ae1-11eb-92f0-be6c2016fe73.png)

Chrome 87.0.4280.88 (x86_64)
Firefox 82.0.2 (64 bits)

**Comment by Deleplace** [comment]
Same for Safari
![image](https://user-images.githubusercontent.com/13508141/101765455-9eba6380-3ae1-11eb-88d4-76e204dc0ea9.png)

Safari Version 14.0 (15610.1.28.1.9, 15610)

**Comment by tomayac** [comment]
Thanks for the report. This was just fixed with https://github.com/tomayac/joy-con-webhid/commit/a19e541b365305eb440998b3a329989ddb361952. The `tl;dr` is that you need an origin trial token (or set the experimental web platform features flag in Chrome). The demo was missing the token. Please try again now.

**Comment by Deleplace** [comment]
It works!! Thanks

**Comment by Deleplace** [comment]
Though for some reason on the left joycon the buttons work, but not the accelerometer/gyroscope.

**Comment by tomayac** [comment]
Glad to hear. Try re-pairing and reloading the page. Wake up the Joy-Cons before by pressing buttons. 

Also plug them in your Switch and update the firmware. It’s become a lot better for one of my pairs when I did that.
