### ISSUE TITLE
can't connect via USB

### ISSUE THREAD

**Issue by taisukef** [tomayac/joy-con-webhid#13]
SNES Controller, N64 Controller, MD/Gen Control Pad can connect via USB also, but this driver couldn't support yet.
The devices are detected, but can't get 'inputreport'.

**Comment by taisukef** [comment]
I found info!
https://www.mzyy94.com/blog/2020/03/20/nintendo-switch-pro-controller-usb-gadget/

**Comment by tomayac** [comment]
Fixed via #14.
