### ISSUE TITLE
Control the refresh rate

### ISSUE THREAD

**Issue by JerryI** [tomayac/joy-con-webhid#23]
Great project! 
Is it possible to control the refresh-rate on a hardware level? Or is it coded somewhere

**Comment by tomayac** [comment]
The controllers send low-level events whenever they are observed, and the library surfaces them to you as high-level events. [This line](https://github.com/tomayac/joy-con-webhid/blob/d74cfa2d830e61f1e529b8c7826a516423ef09a1/src/joycon.js#L51) is where this happens.
