### ISSUE TITLE
NotAllowedError Failed to open the device

### ISSUE THREAD

**Issue by derwehr** [tomayac/joy-con-webhid#3]
When trying out any of the 2 demos, after clicking connect on the webBluetooth dialog, I always get the following Output in the Console:

```
HID connected: Joy-Con (L)

Uncaught (in promise) DOMException: Failed to open the device.

NotAllowedError Failed to open the device.
connectJoyCon @ index.js:42
```

(I did connect to JoyCon to my Computer via my computer's bluetooth settings before, otherwise they don't show up in the webBluetooth dialog.)

The JoyCon I'm using is brand-new and hasn't been connected to a switch before, do I have to install some kind of firmware on the JoyCon first or should the demos work with devices right out of the box?

**Comment by tomayac** [comment]
It may be that the controller needs a firmware update. Try connecting it to a Switch and [checking for firmware updates](https://en-americas-support.nintendo.com/app/answers/detail/a_id/26321/~/how-to-update-the-controller-firmware). Can you then also try the [demo](https://webhid-joycon-button.glitch.me/) linked from the [article](https://web.dev/hid/#receive-input-reports) (Glitch seems to have a Bad Gateway issue at the moment) and let me know if it worked?

**Comment by tomayac** [comment]
(After connecting the controllers to the Switch, be sure to turn the Switch off or turn on airplane mode, else, the Switch won't let you connect to the controller with your computer and instead stay connected to it.)

**Comment by derwehr** [comment]
> It may be that the controller needs a firmware update. Try connecting it to a Switch and [checking for firmware updates](https://en-americas-support.nintendo.com/app/answers/detail/a_id/26321/~/how-to-update-the-controller-firmware). Can you then also try the [demo](https://webhid-joycon-button.glitch.me/) linked from the [article](https://web.dev/hid/#receive-input-reports) (Glitch seems to have a Bad Gateway issue at the moment) and let me know if it worked?

Thanks for the fast response.
I get the same error on the demo mentioned above:

```
script.js:67 Uncaught (in promise) DOMException: Failed to open the device.
openButton.onclick @ script.js:67
async function (async)
openButton.onclick @ script.js:52
```

I'll try to get my hands on a switch to update the Joy-Cons firmware and give you an update then.

**Comment by derwehr** [comment]
The issue persisted after connecting my joy-cons to a switch and updating their firmware.
However, I found out that this isa Linux issue. The Demo works fine on a windows machine.

**Comment by tomayac** [comment]
Thanks for updating the issue. In this case we can close it here, and you should report it as a [new Linux issue](https://bugs.chromium.org/p/chromium/issues/entry?template=Defect+on+Linux). If you let me know the bug ID here, I can help triage.

**Comment by tomayac** [comment]
Thank you `<3` for sharing the solution. I'll point to here from the `README`.
