### ISSUE TITLE
Finer control of Rumble

### ISSUE THREAD

**Issue by Prid13** [tomayac/joy-con-webhid#4]
Incredible work on this -- it's amazing how I can use my joy-con in my browser through javascript :D

I tried the rumble function on your demo page, and I'm blown away that it's even possible to control it!

However, it only allows for a single, long-lasting vibration. Would it be possible to control the duration as well? I'd really like to generate more nuanced HD Rumble vibrations, and even play sound from the joy cons :)

Also, what's the difference between low frequency and high frequency parameters for the `rumble` function? I can't seem to understand that :(

Thanks!

**Comment by tomayac** [comment]
Thanks for the kind words. You should be able to fine-tune the rumbles by playing with the parameters of https://github.com/tomayac/joy-con-webhid/blob/6ebaccf4dfd58cf6b1aae9fb2a706fead665ef72/demo/index.js#L87. 

Low frequency and high frequency is based on different haptics actuators in the controllers. By combining them, different effects like wobbling can be created.

**Comment by Prid13** [comment]
I've already done that, but that only tweaks the frequency and amplitude. The generated soundwave/rumble still plays for 2-3 seconds per call of the `rumble` function. I would like to be able to control for how long a single rumble (i.e. call of the `rumble` function) lasts/plays for.

For instance, `joyCon.rumble(600, 600, 0.5); ` will generate a rumble that lasts for 2-3 seconds. There's no way to turn if off after 0.5 seconds, or make it last for only 0.1 seconds.

**WAIT, nevermind**, I just realized that calling `rumble` again with different parameters actually stops the previous rumble and plays the new one :O I just tried calling `rumble(600, 600, 0)` after 0.1 seconds of playing the normal one, and the rumble stopped :D I was under the impression that the next rumble call only played after the current one had ended (after 2-3 seconds). I'm sorry for throwing all this confusion and wall of text at you, but I had no way of knowing how to use this function, but it's actually working -- holy God, it's actually working! I've got all these cool ideas that I want to try out with the joy con rumbles.

Thank you soo much for the reply and for pointing me in the right direction 😇⭐🎉

**Comment by tomayac** [comment]
I would appreciate a quick PR where you add a sample to the README. If one person is unsure how to use it, probably others are, too. Thanks for helping out in advance, should you decide to do so. `<3`

**Comment by Prid13** [comment]
I love that mentality of wanting to help out new people who might be confused at first, and as a precautionary step at that ⭐! As if the project wasn't impressive already, you've also got an understanding and beginner-friendly mindset -- bravo 👏💯

I'll write that README file as soon I get to experimenting a bit with the rumble API :)

**Comment by meduzen** [comment]
I’m watching the repo and saw this conversation, and it’s only jumping to my mind now: yes, if at anytime you use `0` as vibration pattern, the Vibration API stops any ongoing vibration.

I figured this out while developing this [lil' block](https://block.sunappu.net/) ([source code](https://github.com/Sunappu-Dojo/burokku/blob/master/src/js/helpers/Rumble/index.js#L52): feel free to ask any question, now I remember about it 😅).

**Comment by Prid13** [comment]
@meduzen thanks for chiming in with your 2 cents, I appreciate it :) Wait, so there's an official Vibration API :O? I thought this project was simply sending commands to trigger the rumble in the joycon hardware? Is it somehow tied to an official implementation of a Vibration API, which I didn't even know existed? Would love some clarification since you're offering to assist :)

**Comment by meduzen** [comment]
> I thought this project was simply sending commands to trigger the rumble in the joycon hardware?

You’re absolutely right. My bad (a bit tired these days 😅). Indeed the project sends the commands to the Joy-Con, and it’s very different from the [web Vibration API capabilities](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate) (which is basically: “vibrate during {provided duration}”, where the duration is in milliseconds and can be 1 number or an array of numbers).

Looking at the [rumble signature](https://github.com/tomayac/joy-con-webhid/blob/29435e0c8b307147e1f2cb067c141b42a1053753/src/joycon.js#L260) (`rumble(lowFrequency, highFrequency, amplitude)`), it’s indeed very different than a set of durations.

I was thus completely off-topic. 🙃

**Comment by Prid13** [comment]
@meduzen hey, no worries at all. The simple fact that you wanted to help out a lost person in need here says a lot about you and your intentions, and that's honestly all that matters to me 😇⭐ I appreciate that you even commented here in the first place, and I just learnt of the web Vibration API's existence -- that's a win for me :)

**Comment by meduzen** [comment]
Ha ha, glad you enjoy it. I have more ideas in the pipe for this small block. Planned for later this year. :p I’ll keep you posted.
